services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      npm install
      npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT